version: '3'

services:
#  app:
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: verygoodpassword
      MYSQL_DATABASE: app
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    environment:
      MYSQL_ROOT_PASSWORD: verygoodpassword
      PMA_HOST: db
    ports:
      - 8081:80

volumes:
  db_data: